version: '3.3'
services:

  ureplicator:
    build:
      context: ./ureplicator
      dockerfile: ./Dockerfile.ureplicator
    image: ureplicator:latest
    # image: danielcoman/ureplicator:latest

  # kafka-small-ureplicator:
  #   build:
  #     context: ./kafka
  #     dockerfile: ./Dockerfile
  #   image: danielcoman/kafka-small-ureplicator:latest
