apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  namespace: mirror-maker
  name: mirror-maker-worker
  labels:
    app: mirror-maker
    component: worker
spec:
  replicas: 0
  selector:
    matchLabels:
      app: mirror-maker
      component: worker
  template:
    metadata:
      labels:
        app: mirror-maker
        component: worker
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: mirror-maker-worker
        image: solsson/kafka:1.0.1@sha256:1a4689d49d6274ac59b9b740f51b0408e1c90a9b66d16ad114ee9f7193bab111
        command:
        - ./bin/kafka-mirror-maker.sh
        -  "--consumer.config=/mirror-maker/config/consumer.properties"
        -  "--producer.config=/mirror-maker/config/producer.properties"
        -  --new.consumer
        # -  --whitelist='.*'
        -  "--whitelist='test'"
        -  "--offset.commit.interval.ms=1000"
        env:
        - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
          value: "123"
        - name: KAFKA_LOG4J_OPTS
          value: -Dlog4j.configuration=file:/etc/kafka/log4j.properties
        - name: JMX_PORT
          value: "5555"
        ports:
        - name: jmx
          containerPort: 5555
        resources:
          requests:
            cpu: 100m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 2000Mi
        volumeMounts:
          - name: config
            mountPath: /etc/kafka
          - name: mirror-maker-config-volume
            mountPath: /mirror-maker/config/consumer.properties
            subPath: consumer.properties
          - name: mirror-maker-config-volume
            mountPath: /mirror-maker/config/producer.properties
            subPath: producer.properties
      - name: metrics
        image: solsson/kafka-prometheus-jmx-exporter@sha256:a23062396cd5af1acdf76512632c20ea6be76885dfc20cd9ff40fb23846557e8
        command:
        - java
        - -XX:+UnlockExperimentalVMOptions
        - -XX:+UseCGroupMemoryLimitForHeap
        - -XX:MaxRAMFraction=1
        - -XshowSettings:vm
        - -jar
        - jmx_prometheus_httpserver.jar
        - "5556"
        - /etc/jmx-kafka/jmx-kafka-prometheus.yml
        ports:
        - containerPort: 5556
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            memory: 200Mi
        volumeMounts:
        - name: jmx-config
          mountPath: /etc/jmx-kafka
      volumes:
        - name: config
          configMap:
            name: broker-config
        - name: mirror-maker-config-volume
          configMap:
            name: mirror-maker-config
        - name: jmx-config
          configMap:
            name: jmx-config
      nodeSelector:
        worker: "true"
